version: '3'

services:
  crawler_servidor:
    build: .       
    container_name: servidores_executivo
    command: python main.py
    ports:
      - "8787:8000"
    volumes:
      - ${DATALAKE_PATH}:/datalake
      - "/etc/localtime:/etc/localtime:ro"
      # - ${BIBLIOTECA}
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_IN_TOPIC=${KAFKA_IN_TOPIC}
      - KAFKA_LOG_TOPIC=${KAFKA_LOG_TOPIC}
      - DATALAKE_PATH=${DATALAKE_PATH}
      - TZ=America/Sao_Paulo

